spring.application.name=JobAppRest

spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=0719
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secretKey = djfoispoiajenvaskmhwhrieorgjvmkdfmvaooouaoejmvxmnvkjdhdfhs
spring.security.user.name=piyush
spring.security.user.password=0719

spring.security.oauth2.client.registration.google.client-id=1073367381106-gv4kokmmq8ljnvhiet3sd0i77tb0qbvd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=Ov23liME8sb5UajFtibn
spring.security.oauth2.client.registration.github.client-secret=279d8f4d4f03d0d0831fea1eac88213275336b97

